<a href="https://colab.research.google.com/github/lizsenati19-debug/EXAMEN-FINAL/blob/main/Examen_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **EXAMEN - FINAL**

***Parte 1: Fundamentos NumPy***

*1) Crear un arreglo del 1 al 20 con np.arange(1,21).*

In [2]:
import numpy as np

arreglo = np.arange(1, 21)

print(arreglo)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


*2) Filtrar múltiplos de 3 usando condiciones (arr[arr % 3 == 0]).*

In [3]:
import numpy as np

arreglo = np.arange(1, 21)
multiplos_3 = arreglo[arreglo % 3 == 0]

print(multiplos_3)


[ 3  6  9 12 15 18]


`3) Generar matriz aleatoria 5x5 con np.random.rand(5,5).`

In [4]:
import numpy as np

matriz = np.random.rand(5, 5)

print(matriz)


[[0.55841518 0.23877512 0.45210069 0.40255506 0.07475318]
 [0.98882306 0.25225185 0.4375601  0.28812879 0.34816147]
 [0.07219361 0.13984142 0.49868328 0.27539244 0.3738672 ]
 [0.8362742  0.5681367  0.84561202 0.95564682 0.05931861]
 [0.45690518 0.13055577 0.71366067 0.63174615 0.74388264]]


*4. Calcular media, desviación estándar y máximo con .mean(), .std(), .max().*

In [28]:
import numpy as np

matriz = np.random.rand(5, 5)

media = matriz.mean()
desviacion = matriz.std()
maximo = matriz.max()

print("Matriz:\n", matriz ,"\n")
print("Media:", media)
print("Desviacion estandar:", desviacion)
print("Maximo:", maximo)


Matriz:
 [[0.33579029 0.89612338 0.00268375 0.8122495  0.6160679 ]
 [0.59443051 0.11004211 0.19367538 0.48599314 0.3497239 ]
 [0.96474275 0.69861326 0.8556067  0.96005038 0.50795915]
 [0.39491052 0.54720207 0.93844907 0.57806813 0.29734075]
 [0.39738284 0.49396031 0.16009304 0.62093537 0.13254632]] 

Media: 0.5177856196342008
Desviacion estandar: 0.2781286205929507
Maximo: 0.9647427498842532


*5. Transformar matriz en vector con .flatten().*

In [8]:
import numpy as np

matriz = np.random.rand(5, 5)

vector = matriz.flatten()

print("Matriz:\n", matriz)
print("\nVector:\n", vector)


Matriz:
 [[0.63714147 0.61964736 0.43014738 0.1382806  0.10596907]
 [0.94986184 0.72595079 0.60606977 0.72567678 0.61319406]
 [0.19484756 0.56713985 0.54654268 0.91825258 0.94096135]
 [0.94030817 0.67987208 0.71594983 0.66268368 0.05506274]
 [0.92887725 0.77069767 0.48343911 0.71110008 0.20865732]]

Vector:
 [0.63714147 0.61964736 0.43014738 0.1382806  0.10596907 0.94986184
 0.72595079 0.60606977 0.72567678 0.61319406 0.19484756 0.56713985
 0.54654268 0.91825258 0.94096135 0.94030817 0.67987208 0.71594983
 0.66268368 0.05506274 0.92887725 0.77069767 0.48343911 0.71110008
 0.20865732]


***Parte 2: Fundamentos Pandas***

*1. Crear un DataFrame con los datos de estudiantes.*

In [30]:
import numpy as np
import pandas as pd
data = {
    "Nombre": ["Ana", "Luis", "Maria", "Pedro", "Sofia"],
    "Edad": [20, 21, 19, 22, 20],
    "Nota_Matematicas": [18, 15, 16, 12, 19],
    "Nota_IA": [17, 14, 18, 13, 20]
}
df = pd.DataFrame(data)
print(df)


  Nombre  Edad  Nota_Matematicas  Nota_IA
0    Ana    20                18       17
1   Luis    21                15       14
2  Maria    19                16       18
3  Pedro    22                12       13
4  Sofia    20                19       20


*2. Calcula el promedio de cada columna numérica.*

In [11]:
import numpy as np
import pandas as pd
print("\nPromedio por columna:\n", df.mean(numeric_only=True))


Promedio por columna:
 Edad                20.4
Nota_Matemáticas    16.0
Nota_IA             16.4
dtype: float64


*3. Filtra los estudiantes con nota de IA mayor a 15*

In [37]:
print("\nEstudiantes con Nota IA > 15:\n")
print(df[df["Nota_IA"] > 15][["Nombre", "Edad", "Nota_IA"]])



Estudiantes con Nota IA > 15:

  Nombre  Edad  Nota_IA
0    Ana    20       17
2  Maria    19       18
4  Sofia    20       20


*4. Agrega una nueva columna llamada Promedio que contenga el promedio de
Nota_Matemáticas y Nota_IA.*

In [43]:
df["Promedio"] = (df["Nota_Matematicas"] + df["Nota_IA"]) / 2
print(df)

  Nombre  Edad  Nota_Matematicas  Nota_IA  Promedio
0    Ana    20                18       17      17.5
1   Luis    21                15       14      14.5
2  Maria    19                16       18      17.0
3  Pedro    22                12       13      12.5
4  Sofia    20                19       20      19.5


*5. Ordena el DataFrame según la columna Promedio de mayor a menor.*

In [44]:
df_ordenado = df.sort_values("Promedio", ascending=False)
print(df_ordenado)

  Nombre  Edad  Nota_Matematicas  Nota_IA  Promedio
4  Sofia    20                19       20      19.5
0    Ana    20                18       17      17.5
2  Maria    19                16       18      17.0
1   Luis    21                15       14      14.5
3  Pedro    22                12       13      12.5


***Parte 3: Algoritmia aplicada***

*1. Escribe una función en Python que reciba una lista de números y devuelva:
o El número mayor
o El número menor
o El promedio*

In [53]:
import numpy as np
import pandas as pd

def analizar_lista(lista):
    return max(lista), min(lista), sum(lista) / len(lista)

nums = [5, 8, 2, 10, 3]
mayor, menor, promedio = analizar_lista(nums)

print("\nLista:", nums)
print(f"Mayor:    {mayor}")
print(f"Menor:    {menor}")
print(f"Promedio: {promedio:.2f}")



Lista: [5, 8, 2, 10, 3]
Mayor:    10
Menor:    2
Promedio: 5.60


*2. Usando NumPy, implementa una función de activación Sigmoide definida como:
f(x)=11+e−xf(x) = \frac{1}{1 + e^{-x}}f(x)=1+e−x1
Aplica la función a un arreglo x = np.array([-2, -1, 0, 1, 2]).*

In [56]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.array([-2, -1, 0, 1, 2])

resultado = sigmoid(x)
print("Arreglo original:", x)
print("Sigmoide aplicada:", resultado)


Arreglo original: [-2 -1  0  1  2]
Sigmoide aplicada: [0.11920292 0.26894142 0.5        0.73105858 0.88079708]


*3. Crea una función que clasifique a los estudiantes del DataFrame en "Aprobado"
si su Promedio ≥ 14, y "Desaprobado" en caso contrario. Añade una nueva
columna llamada Estado.*

In [57]:
df["Estado"] = np.where(df["Promedio"] >= 14, "Aprobado", "Desaprobado")
print(df)

  Nombre  Edad  Nota_Matematicas  Nota_IA  Promedio       Estado
0    Ana    20                18       17      17.5     Aprobado
1   Luis    21                15       14      14.5     Aprobado
2  Maria    19                16       18      17.0     Aprobado
3  Pedro    22                12       13      12.5  Desaprobado
4  Sofia    20                19       20      19.5     Aprobado


***Parte 4: Mini-proyecto (Ventas)***

*1. Agrega una nueva columna llamada Crecimiento que calcule el porcentaje de
crecimiento entre Ventas_2024 y Ventas_2025*

In [58]:
import numpy as np
import pandas as pd

ventas = {
    "Producto": ["A", "B", "C", "D"],
    "Ventas_2024": [100, 150, 200, 250],
    "Ventas_2025": [120, 180, 260, 270]
}
df_ventas = pd.DataFrame(ventas)

df_ventas["Crecimiento"] = ((df_ventas["Ventas_2025"] - df_ventas["Ventas_2024"]) / df_ventas["Ventas_2024"]) * 100
df_ventas["Crecimiento"] = df_ventas["Crecimiento"].apply(lambda x: f"{x:.2f}%")

print("\nDataFrame de ventas con Crecimiento (%):\n", df_ventas)



DataFrame de ventas con Crecimiento (%):
   Producto  Ventas_2024  Ventas_2025 Crecimiento
0        A          100          120      20.00%
1        B          150          180      20.00%
2        C          200          260      30.00%
3        D          250          270       8.00%


*2. Identifica el producto con mayor crecimiento y muéstralo.*

In [65]:
producto_max = df_ventas.loc[df_ventas["Crecimiento"].str.rstrip('%').astype(float).idxmax()]
print("\nProducto con mayor crecimiento:\n", producto_max)


Producto con mayor crecimiento:
 Producto            C
Ventas_2024       200
Ventas_2025       260
Crecimiento    30.00%
Name: 2, dtype: object


***Parte 5: Resolución de ecuaciones***


*1. Ecuación de primer grado
o Implementa una función en Python que resuelva una ecuación de la forma:
ax+b=0ax + b = 0ax+b=0
por ejemplo: 2x + 4 = 0.
o La función debe retornar el valor de x.*

In [67]:
import numpy as np
import pandas as pd
def ecuacion_1grado(a, b):
    return -b / a

print("\nEcuación: 2x + 4 = 0, \n"
"Solución x =", ecuacion_1grado(2, 4))


Ecuación: 2x + 4 = 0, 
Solución x = -2.0


*2. Ecuación de segundo grado
o Implementa una función en Python que resuelva una ecuación de la forma:
ax2+bx+c=0ax^2 + bx + c = 0ax2+bx+c=0
usando la fórmula general:
x=−b±b2−4ac2ax = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}x=2a−b±b2−4ac
o La función debe retornar las dos soluciones (reales o complejas).*

In [73]:
import numpy as np

def ecuacion_2grado(a, b, c):
    disc = b**2 - 4*a*c
    if disc >= 0:
        x1 = (-b + np.sqrt(disc)) / (2*a)
        x2 = (-b - np.sqrt(disc)) / (2*a)
    else:
        x1 = (-b + np.lib.scimath.sqrt(disc)) / (2*a)
        x2 = (-b - np.lib.scimath.sqrt(disc)) / (2*a)
    return x1, x2

sol1, sol2 = ecuacion_2grado(1, -5, 6)
print(f"Las dos soluciones son:\n"
      f"x1 = {sol1} \n"
      f"x2 = {sol2}")

Las dos soluciones son:
x1 = 3.0 
x2 = 2.0
